/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TodoPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const TodoId = IDL.Text;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TodoStatus = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Todo = IDL.Record({
  'id' : TodoId,
  'status' : TodoStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'priority' : TodoPriority,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTodo' : IDL.Func(
      [IDL.Text, IDL.Text, TodoPriority, IDL.Opt(IDL.Text)],
      [TodoId],
      [],
    ),
  'deleteTodo' : IDL.Func([TodoId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTodo' : IDL.Func([TodoId], [Todo], ['query']),
  'getTodoStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'pending' : IDL.Nat,
          'done' : IDL.Nat,
          'inProgress' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTodos' : IDL.Func([], [IDL.Vec(Todo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleStatus' : IDL.Func([TodoId], [], []),
  'updateTodo' : IDL.Func(
      [TodoId, IDL.Text, IDL.Text, TodoPriority, TodoStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TodoPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TodoId = IDL.Text;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TodoStatus = IDL.Variant({
    'pending' : IDL.Null,
    'done' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Todo = IDL.Record({
    'id' : TodoId,
    'status' : TodoStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'priority' : TodoPriority,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTodo' : IDL.Func(
        [IDL.Text, IDL.Text, TodoPriority, IDL.Opt(IDL.Text)],
        [TodoId],
        [],
      ),
    'deleteTodo' : IDL.Func([TodoId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTodo' : IDL.Func([TodoId], [Todo], ['query']),
    'getTodoStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'pending' : IDL.Nat,
            'done' : IDL.Nat,
            'inProgress' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTodos' : IDL.Func([], [IDL.Vec(Todo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleStatus' : IDL.Func([TodoId], [], []),
    'updateTodo' : IDL.Func(
        [
          TodoId,
          IDL.Text,
          IDL.Text,
          TodoPriority,
          TodoStatus,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };