/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Todo {
  'id' : TodoId,
  'status' : TodoStatus,
  'title' : string,
  'createdAt' : bigint,
  'dueDate' : [] | [string],
  'description' : string,
  'priority' : TodoPriority,
}
export type TodoId = string;
export type TodoPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TodoStatus = { 'pending' : null } |
  { 'done' : null } |
  { 'inProgress' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTodo' : ActorMethod<
    [string, string, TodoPriority, [] | [string]],
    TodoId
  >,
  'deleteTodo' : ActorMethod<[TodoId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTodo' : ActorMethod<[TodoId], Todo>,
  'getTodoStats' : ActorMethod<
    [],
    {
      'total' : bigint,
      'pending' : bigint,
      'done' : bigint,
      'inProgress' : bigint,
    }
  >,
  'getTodos' : ActorMethod<[], Array<Todo>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleStatus' : ActorMethod<[TodoId], undefined>,
  'updateTodo' : ActorMethod<
    [TodoId, string, string, TodoPriority, TodoStatus, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];